// <auto-generated/>
using ReactiveUI;
using ReactiveUI.Reactive;

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class GeneratedOnlyModel
    {
        /// <inheritdoc cref="_email"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string Email
        {
            get => _email;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_email")]
            set
            {
                this.RaiseAndSetIfChanged(ref _email, value);
            }
        }

        /// <inheritdoc cref="_rule"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper? Rule
        {
            get => _rule;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_rule")]
            set
            {
                this.RaiseAndSetIfChanged(ref _rule, value);
            }
        }

        /// <inheritdoc cref="_selectedContext"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext? SelectedContext
        {
            get => _selectedContext;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_selectedContext")]
            set
            {
                this.RaiseAndSetIfChanged(ref _selectedContext, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore
