// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ReactiveUI.Validation.SourceGenerators;

/// <summary>Places exact typed accessors inside an existing legal partial enclosing type.</summary>
internal static class AccessBridgeLexicalHost
{
    /// <summary>Finds an augmentable enclosing type that a global interceptor can name.</summary>
    /// <param name="compilation">The actual caller compilation.</param>
    /// <param name="owner">The inaccessible accessor owner.</param>
    /// <returns>The constructed lexical host, or no legal host.</returns>
    internal static INamedTypeSymbol? Find(Compilation compilation, INamedTypeSymbol owner)
    {
        for (var host = owner; host is not null; host = host.ContainingType)
        {
            if (CanName(compilation, host) && CanAugment(host))
            {
                return host;
            }
        }

        return null;
    }

    /// <summary>Wraps a nested typed bridge in the host's existing partial declarations.</summary>
    /// <param name="host">The proven accessible enclosing host.</param>
    /// <param name="bridge">The complete nested bridge declaration.</param>
    /// <returns>The source compilation unit without any type-name based accessors.</returns>
    internal static string Wrap(INamedTypeSymbol host, string bridge)
    {
        var types = new Stack<INamedTypeSymbol>();
        for (var current = host; current is not null; current = current.ContainingType)
        {
            types.Push(current.OriginalDefinition);
        }

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        var hasNamespace = !host.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            _ = source.Append("namespace ").Append(host.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        }

        var count = types.Count;
        while (types.Count > 0)
        {
            AppendDeclaration(source, types.Pop());
        }

        _ = source.AppendLine(bridge).Append('}', count);
        if (hasNamespace)
        {
            _ = source.Append('}');
        }

        return source.ToString();
    }

    /// <summary>Requires the full constructed host to remain nameable at the outward transport call.</summary>
    /// <param name="compilation">The exact caller compilation.</param>
    /// <param name="type">The proposed host or a nested argument.</param>
    /// <returns>Whether an assembly-level caller can name its complete type syntax.</returns>
    private static bool CanName(Compilation compilation, ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => true,
        IArrayTypeSymbol array => CanName(compilation, array.ElementType),
        INamedTypeSymbol named => !named.IsFileLocal && compilation.IsSymbolAccessibleWithin(named.OriginalDefinition, compilation.Assembly)
            && (named.ContainingType is null || CanName(compilation, named.ContainingType)) && named.TypeArguments.All(argument => CanName(compilation, argument)),
        _ => false,
    };

    /// <summary>Requires every containing declaration to be an actual non-file-local partial class.</summary>
    /// <param name="host">The proposed enclosing host.</param>
    /// <returns>Whether generated source can legally augment the declaration chain.</returns>
    private static bool CanAugment(INamedTypeSymbol host)
    {
        for (var current = host; current is not null; current = current.ContainingType)
        {
            if (current.IsFileLocal || current.IsAnonymousType || current.IsRefLikeType || current.TypeKind is not (TypeKind.Class or TypeKind.Struct)
                || current.DeclaringSyntaxReferences.IsEmpty || current.DeclaringSyntaxReferences.Any(static reference => reference.GetSyntax() is not TypeDeclarationSyntax declaration
                    || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>Copies a host declaration with its original parameter names and constraints.</summary>
    /// <param name="source">The generated compilation unit.</param>
    /// <param name="type">The original partial type definition.</param>
    private static void AppendDeclaration(StringBuilder source, INamedTypeSymbol type)
    {
        _ = source.Append("partial ").Append(DeclarationKind(type)).Append(" @").Append(type.Name);
        if (!type.TypeParameters.IsEmpty)
        {
            _ = source.Append('<').Append(string.Join(", ", type.TypeParameters.Select(static parameter => $"@{parameter.Name}"))).Append('>');
        }

        foreach (var parameter in type.TypeParameters)
        {
            _ = source.Append(GenericInterceptorEmitter.Constraints(parameter));
        }

        _ = source.AppendLine(" {");
    }

    /// <summary>Retains the existing class, struct or record declaration shape.</summary>
    /// <param name="type">The original source host.</param>
    /// <returns>The legal partial declaration keywords.</returns>
    private static string DeclarationKind(INamedTypeSymbol type) => (type.IsRecord, type.TypeKind) switch
    {
        (true, TypeKind.Struct) => "record struct",
        (true, _) => "record class",
        (false, TypeKind.Struct) => "struct",
        _ => "class",
    };
}
