// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace ReactiveUI.Validation.SourceGenerators;

/// <summary>Places typed bodies in legal lexical hosts and forwards through original API slots.</summary>
[SuppressMessage("Performance", "PSH1100", Justification = "This is compiler-time planning and source formatting over bounded immutable operations, not emitted subscription execution.")]
internal static class HostedPlanEmitter
{
    /// <summary>The stable FNV-1a multiplication factor.</summary>
    private const uint FnvPrime = 16_777_619U;

    /// <summary>Wraps a concrete body or creates a lexical payload bridge.</summary>
    /// <param name="site">The original call.</param>
    /// <param name="body">The concrete statements without method header or braces.</param>
    /// <param name="source">The complete global interceptor.</param>
    /// <param name="reason">The required explicit typed factory alternative.</param>
    /// <param name="forceHost">Whether member access requires lexical placement.</param>
    /// <returns>Whether a legal typed wrapper exists.</returns>
    [SuppressMessage("Style", "SST1442", Justification = "The placement decision independently checks direct specialization, closed access and lexical partial hosting.")]
    internal static bool TryWrap(CallSite site, string body, out string source, out string reason, bool forceHost = false)
    {
        reason = string.Empty;
        if (!forceHost && !site.RequiresLexicalAccess && GenericInterceptorEmitter.CanSpecialize(site))
        {
            var rebound = TypeParameterSyntax.ReplaceCode(body, GenericInterceptorEmitter.DirectSubstitutions(site));
            source = $"{site.Attribute}\n{GeneratorHelpers.MethodHeader(site)}\n{{\n{rebound}\n}}";
            return true;
        }

        if (!forceHost && !site.RequiresLexicalAccess && !GenericInterceptorEmitter.NeedsOriginalSignature(site))
        {
            source = $"{site.Attribute}\n{GeneratorHelpers.MethodHeader(site)}\n{{\n{body}\n}}";
            return true;
        }

        source = string.Empty;
        if (site.Method.TypeArguments.Any(static argument => argument is INamedTypeSymbol { IsAnonymousType: true })
            || site.Method.Parameters[0].Type is not INamedTypeSymbol host || !CanHost(host))
        {
            reason = "This source has no legal partial lexical host."
                + "Construct an inferred typed ValidationSelector/ValidationTarget factory in the caller's access context, or use the scoped typed catalog route.";
            return false;
        }

        var original = site.Method.OriginalDefinition;
        var identity = $"ValidationSite_{site.Id}_{StableId(site.Invocation.SyntaxTree.FilePath)}_{site.Invocation.SpanStart}";
        var assembly = ValidationGenerator.AssemblyIdentity(site.Model.Compilation.AssemblyName ?? "Application");
        var namespaceName = $"ReactiveUI.Validation.Generated.{assembly}.Hosts";
        var apiParameters = original.TypeParameters;
        var slots = apiParameters.IsEmpty ? string.Empty : $"<{string.Join(", ", apiParameters.Select(static type => $"@{type.Name}"))}>";
        var actualSlots = site.Method.TypeArguments.IsEmpty ? string.Empty : $"<{string.Join(", ", site.Method.TypeArguments.Select(GeneratorHelpers.TypeName))}>";
        var contract = $"global::{namespaceName}.{identity}{slots}";
        var closedContract = TypeParameterSyntax.ReplaceType($"global::{namespaceName}.{identity}{actualSlots}", HostSubstitutions(host));
        var interfaceSource = new StringBuilder($"// <auto-generated/>\n#nullable enable\nnamespace {namespaceName} {{\ninternal interface {identity}{slots}");
        foreach (var parameter in apiParameters)
        {
            _ = interfaceSource.Append(GenericInterceptorEmitter.Constraints(parameter, includeNotNull: false));
        }

        _ = interfaceSource.AppendLine(" {").Append(GeneratorHelpers.TypeName(original.ReturnType)).Append(" Execute(")
            .Append(ParameterList(original)).AppendLine(");\n}\n}");
        var returnType = TypeParameterSyntax.ReplaceType(GeneratorHelpers.TypeName(site.Method.ReturnType), HostSubstitutions(host));
        var hostSource = BuildHost(
            host,
            closedContract,
            $"{returnType} {closedContract}.Execute({HostParameterList(host, site.Method)})\n{{\n{RebindHost(host, body)}\n}}");
        site.AdditionalSources.Add(new($"{identity}.Contract.g.cs", interfaceSource.ToString()));
        site.AdditionalSources.Add(new($"{identity}.Host.g.cs", hostSource));
        var arguments = string.Join(", ", original.Parameters.Select(static parameter => $"{RefArgument(parameter)}@{parameter.Name}"));
        var receiver = $"@{original.Parameters[0].Name}";
        source = $"{site.Attribute}\n{GeneratorHelpers.MethodHeader(site)}\n{{\nreturn (({contract}){receiver}).Execute({arguments});\n}}";
        return true;
    }

    /// <summary>Tests whether all containing declarations can be augmented legally.</summary>
    /// <param name="host">The model or view receiver.</param>
    /// <returns>Whether a lexical partial bridge can be emitted.</returns>
    private static bool CanHost(INamedTypeSymbol host)
    {
        for (var current = host; current is not null; current = current.ContainingType)
        {
            if (current.IsFileLocal || current.IsAnonymousType || current.IsRefLikeType || current.TypeKind != TypeKind.Class
                || current.DeclaringSyntaxReferences.IsEmpty || current.DeclaringSyntaxReferences.Any(static reference => reference.GetSyntax() is not TypeDeclarationSyntax declaration
                    || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>Formats all original payload parameters, excluding extension syntax.</summary>
    /// <param name="method">The API method.</param>
    /// <returns>The exact typed payload parameter list.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string ParameterList(IMethodSymbol method) => string.Join(", ", method.Parameters.Select(static parameter => RefArgument(parameter)
        + GeneratorHelpers.TypeName(parameter.Type) + " @" + parameter.Name));

    /// <summary>Rebinds each payload type using a type parser rather than an incomplete declaration.</summary>
    /// <param name="host">The constructed lexical host.</param>
    /// <param name="method">The exact API payload.</param>
    /// <returns>The lexical parameter list.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string HostParameterList(INamedTypeSymbol host, IMethodSymbol method) => string.Join(", ", method.Parameters.Select(parameter => RefArgument(parameter)
        + TypeParameterSyntax.ReplaceType(GeneratorHelpers.TypeName(parameter.Type), HostSubstitutions(host)) + " @" + parameter.Name));

    /// <summary>Formats a parameter's exact byref passing contract.</summary>
    /// <param name="parameter">The payload parameter.</param>
    /// <returns>The C# modifier.</returns>
    private static string RefArgument(IParameterSymbol parameter) => parameter.RefKind switch
    {
        RefKind.Ref => "ref ",
        RefKind.Out => "out ",
        RefKind.In or RefKind.RefReadOnlyParameter => "in ",
        _ => string.Empty,
    };

    /// <summary>Builds containing partial declarations around a legal instance adapter.</summary>
    /// <param name="host">The source host.</param>
    /// <param name="contract">The implemented per-site payload contract.</param>
    /// <param name="method">The lexical method body.</param>
    /// <returns>A complete compilation unit.</returns>
    private static string BuildHost(INamedTypeSymbol host, string contract, string method)
    {
        var types = new Stack<INamedTypeSymbol>();
        for (var current = host; current is not null; current = current.ContainingType)
        {
            types.Push(current.OriginalDefinition);
        }

        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        var hasNamespace = !host.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            _ = source.Append("namespace ").Append(host.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        }

        var count = types.Count;
        while (types.Count > 0)
        {
            var type = types.Pop();
            var kind = type.IsRecord ? "record class" : "class";
            _ = source.Append("partial ").Append(kind).Append(" @").Append(type.Name);
            if (!type.TypeParameters.IsEmpty)
            {
                _ = source.Append('<').Append(string.Join(", ", type.TypeParameters.Select(static parameter => $"@{parameter.Name}"))).Append('>');
            }

            if (types.Count == 0)
            {
                _ = source.Append(" : ").Append(contract);
            }

            foreach (var parameter in type.TypeParameters)
            {
                _ = source.Append(GenericInterceptorEmitter.Constraints(parameter));
            }

            _ = source.AppendLine(" {");
        }

        _ = source.AppendLine(method).Append('}', count);
        if (hasNamespace)
        {
            _ = source.Append('}');
        }

        return source.ToString();
    }

    /// <summary>Rebinds caller generic identifiers to the model declaration's own positions.</summary>
    /// <param name="host">The constructed receiver.</param>
    /// <param name="text">The generated lexical body or signature.</param>
    /// <returns>The host-scoped C# text.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string RebindHost(INamedTypeSymbol host, string text) => TypeParameterSyntax.ReplaceCode(text, HostSubstitutions(host));

    /// <summary>Maps caller type parameters to the host declaration's original positions.</summary>
    /// <param name="host">The constructed host.</param>
    /// <returns>The proven declaration slot map.</returns>
    private static Dictionary<string, string> HostSubstitutions(INamedTypeSymbol host)
    {
        var substitutions = new Dictionary<string, string>(StringComparer.Ordinal);
        for (var current = host; current is not null; current = current.ContainingType)
        {
            for (var index = 0; index < current.TypeArguments.Length; index++)
            {
                if (current.TypeArguments[index] is ITypeParameterSymbol argument)
                {
                    substitutions[argument.Name] = current.OriginalDefinition.TypeParameters[index].Name;
                }
            }
        }

        return substitutions;
    }

    /// <summary>Creates a deterministic file-path suffix without process-random hashes.</summary>
    /// <param name="value">The source path.</param>
    /// <returns>A stable identifier suffix.</returns>
    private static string StableId(string value)
    {
        var hash = 2_166_136_261U;
        foreach (var character in value)
        {
            hash = (hash ^ character) * FnvPrime;
        }

        return hash.ToString("x8", System.Globalization.CultureInfo.InvariantCulture);
    }
}
