// <auto-generated/>
using ReactiveUI;

#pragma warning disable
#nullable enable

namespace ProjectionInput
{
    public partial class Model
    {
        /// <inheritdoc cref="_name"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string? Name
        {
            get => _name;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("_name")]
            set
            {
                this.RaiseAndSetIfChanged(ref _name, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore
