// <auto-generated/>
#nullable enable
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
{
    public InterceptsLocationAttribute(int version, string data) { }
}
}
namespace ReactiveUI.Validation.Generated.Assembly_ProjectionConsumer_Primitives_producer_first
{
    internal static class ValidationInterceptors
    {
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "8ZIgNXw5XP7LY3wr+cTHwQMDAABPcmlnaW5hbElucHV0LmNz")]
internal static global::ReactiveUI.Validation.Helpers.ValidationHelper Intercept0(this global::ProjectionInput.Model @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::ProjectionInput.Model, global::System.String?>> @viewModelProperty, global::System.Func<global::System.String?, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = ((global::ReactiveUI.Validation.Abstractions.IValidatableViewModel)@viewModel).ValidationContext;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Extensions.GeneratedValidationObservation.Observe<global::System.String?>(
        () => @viewModel.@Name, new global::ReactiveUI.Validation.Extensions.GeneratedValidationProperty(() => @viewModel, "Name"));
    return global::ReactiveUI.Validation.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.States.ValidationState(false, @message),
        new string[] { "Name" });
}

} }