<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NativeValidation.Primitives</AssemblyName>
    <DefineConstants>SAFE_API;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Runic.ReactiveUI.Validation" Version="$(ValidationVersion)" />
    <PackageReference Include="ReactiveUI" Version="26.0.1" />
    <PackageReference Include="Runic.DynamicData" Version="10.0.0-runic.5" />
  </ItemGroup>
</Project>
