// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace ReactiveUI.Validation.SourceGenerators.Producers;

/// <summary>Validates predictions against actual output after every producer finishes.</summary>
internal static class ProducerContractChecker
{
    /// <summary>Reports an actual member differing from the private declaration profile.</summary>
    internal static readonly DiagnosticDescriptor ContractDrift = new(
        "RUVG008",
        "Validation producer contract drift",
        "Producer contract '{0}.{1}' from {2} differs from actual generated output. Expected '{3}', found '{4}'. "
        + "Use matching pinned producer packages, declare the contract explicitly, or supply a typed validation descriptor.",
        "ReactiveUI.Validation.Generation",
        DiagnosticSeverity.Error,
        true,
        customTags: [WellKnownDiagnosticTags.CompilationEnd]);

    /// <summary>Reports unsupported or unverifiable resolved producer versions.</summary>
    internal static readonly DiagnosticDescriptor UnsupportedProfile = new(
        "RUVG009",
        "Unsupported validation producer profile",
        "Validation prediction requires {0}; resolved producer version is '{1}'. Retain the packaged buildTransitive assets "
        + "and use the supported producer cohort, or declare members explicitly and supply typed descriptors.",
        "ReactiveUI.Validation.Generation",
        DiagnosticSeverity.Error,
        true);

    /// <summary>The implemented-interface contract prefix.</summary>
    private const string InterfacePrefix = "interface:";

    /// <summary>The owner metadata argument.</summary>
    private const int OwnerIndex = 0;

    /// <summary>The member contract argument.</summary>
    private const int MemberIndex = 1;

    /// <summary>The expected signature argument.</summary>
    private const int ExpectedIndex = 2;

    /// <summary>The producer profile argument.</summary>
    private const int ProfileIndex = 3;

    /// <summary>The contract attribute argument count.</summary>
    private const int ArgumentCount = 4;

    /// <summary>Writes only inert contract records, never predicted member definitions.</summary>
    /// <param name="projection">The private semantic compilation.</param>
    /// <returns>The assembly contract records.</returns>
    internal static string Records(ProducerProjection projection)
    {
        if (projection.Declarations.IsEmpty)
        {
            return string.Empty;
        }

        var identity = ValidationGenerator.AssemblyIdentity(projection.Compilation.AssemblyName ?? "Application");
        var root = $"ReactiveUI.Validation.Generated.{identity}";
        var output = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        foreach (var group in ProducerProjection.GroupDeclarations(projection.Declarations).Values)
        {
            foreach (var declaration in group)
            {
                AppendDeclaration(output, root, projection.Compilation, declaration);
            }
        }

        _ = output.Append("namespace ").Append(root).AppendLine(" {")
            .AppendLine("[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple=true)]")
            .AppendLine("internal sealed class ValidationProducerContractAttribute : global::System.Attribute {")
            .AppendLine("public ValidationProducerContractAttribute(string owner, string member, string expected, string profile) { }")
            .AppendLine("} }");
        return output.ToString();
    }

    /// <summary>Checks the fully generated compilation, including peer-generated calls.</summary>
    /// <param name="context">The final analyzer context.</param>
    internal static void Analyze(CompilationAnalysisContext context)
    {
        foreach (var attribute in context.Compilation.Assembly.GetAttributes())
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (!TryReadRecord(attribute, context.Compilation.Assembly, out var ownerName, out var member, out var expected, out var profile))
            {
                continue;
            }

            var owner = context.Compilation.GetTypeByMetadataName(ownerName);
            var actual = owner is null ? "missing owner" : FindContract(owner, member);
            if (actual == expected && !expected.StartsWith("missing", StringComparison.Ordinal))
            {
                continue;
            }

            var location = OriginalLocation(owner);
            context.ReportDiagnostic(Diagnostic.Create(ContractDrift, location, ownerName, member, profile, expected, actual));
        }
    }

    /// <summary>Writes the exact expected member/type slot for one prediction.</summary>
    /// <param name="output">The inert record buffer.</param>
    /// <param name="root">The assembly-specific record namespace.</param>
    /// <param name="compilation">The private semantic compilation.</param>
    /// <param name="declaration">The finite prediction.</param>
    private static void AppendDeclaration(StringBuilder output, string root, Compilation compilation, ProducerDeclaration declaration)
    {
        var ownerName = ProducerProjection.MetadataName(declaration.Owner);
        var owner = compilation.GetTypeByMetadataName(ownerName);
        var name = declaration.Name;
        if (declaration.InterfaceName is { } implemented)
        {
            name = $"{InterfacePrefix}{implemented}";
        }
        else if (declaration.BaseType is not null && name.Length == 0)
        {
            name = "base";
        }

        var contract = owner is null ? "missing owner" : FindContract(owner, name);
        AppendRecord(output, root, ownerName, name, contract, declaration.Profile);
        if (declaration.BaseType is not null && name != "base")
        {
            AppendRecord(output, root, ownerName, "base", owner?.BaseType is { } type ? ProducerProjection.TypeName(type) : "missing base", declaration.Profile);
        }
    }

    /// <summary>Appends one escaped inert assembly attribute.</summary>
    /// <param name="output">The record buffer.</param>
    /// <param name="root">The private attribute namespace.</param>
    /// <param name="owner">The declaring metadata name.</param>
    /// <param name="member">The member identity.</param>
    /// <param name="expected">The exact expected signature.</param>
    /// <param name="profile">The pinned producer identity.</param>
    private static void AppendRecord(StringBuilder output, string root, string owner, string member, string expected, string profile) =>
        _ = output.Append("[assembly: global::").Append(root).Append(".ValidationProducerContractAttribute(")
            .Append(Literal(owner)).Append(',').Append(Literal(member)).Append(',').Append(Literal(expected)).Append(',')
            .Append(Literal(profile)).AppendLine(")] ");

    /// <summary>Accepts only this assembly's inert finite contract attribute.</summary>
    /// <param name="attribute">The assembly attribute.</param>
    /// <param name="assembly">The final generated assembly.</param>
    /// <param name="owner">The owner metadata name.</param>
    /// <param name="member">The member contract identity.</param>
    /// <param name="expected">The private expected signature.</param>
    /// <param name="profile">The pinned profile.</param>
    /// <returns>Whether the attribute contains an exact record.</returns>
    private static bool TryReadRecord(AttributeData attribute, IAssemblySymbol assembly, out string owner, out string member, out string expected, out string profile)
    {
        owner = string.Empty;
        member = string.Empty;
        expected = string.Empty;
        profile = string.Empty;
        if (!IsContractAttribute(attribute.AttributeClass, assembly) || attribute.ConstructorArguments.Length != ArgumentCount)
        {
            return false;
        }

        if (attribute.ConstructorArguments[OwnerIndex].Value is not string ownerValue
            || attribute.ConstructorArguments[MemberIndex].Value is not string memberValue
            || attribute.ConstructorArguments[ExpectedIndex].Value is not string expectedValue
            || attribute.ConstructorArguments[ProfileIndex].Value is not string profileValue)
        {
            return false;
        }

        owner = ownerValue;
        member = memberValue;
        expected = expectedValue;
        profile = profileValue;
        return true;
    }

    /// <summary>Rejects user lookalikes and foreign marker assemblies.</summary>
    /// <param name="type">The attribute type.</param>
    /// <param name="assembly">The current generated assembly.</param>
    /// <returns>Whether the inert record type belongs to this compilation.</returns>
    private static bool IsContractAttribute(INamedTypeSymbol? type, IAssemblySymbol assembly) =>
        type is { Name: "ValidationProducerContractAttribute" }
        && SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, assembly)
        && type.ContainingNamespace.ToDisplayString().StartsWith("ReactiveUI.Validation.Generated.Assembly_", StringComparison.Ordinal);

    /// <summary>Locates the original type rather than a predicted declaration tree.</summary>
    /// <param name="owner">The final declaring type.</param>
    /// <returns>A source location or no location.</returns>
    private static Location OriginalLocation(INamedTypeSymbol? owner)
    {
        if (owner is not null)
        {
            foreach (var location in owner.Locations)
            {
                if (location.IsInSource)
                {
                    return location;
                }
            }
        }

        return Location.None;
    }

    /// <summary>Snapshots an exact declaring slot and its assignment/access contract.</summary>
    /// <param name="owner">The declaring type.</param>
    /// <param name="name">The member or type contract identity.</param>
    /// <returns>The exact semantic signature.</returns>
    private static string FindContract(INamedTypeSymbol owner, string name)
    {
        if (name == "base")
        {
            return owner.BaseType is { } baseType ? ProducerProjection.TypeName(baseType) : "missing base";
        }

        if (name.StartsWith(InterfacePrefix, StringComparison.Ordinal))
        {
            var target = name.Substring(InterfacePrefix.Length);
            return HasInterface(owner, target) ? target : MissingInterface(owner, target);
        }

        var members = owner.GetMembers(name);
        if (members.Length != 1)
        {
            return members.IsEmpty ? "missing member" : "ambiguous member";
        }

        return members[0] switch
        {
            IPropertySymbol property => PropertyContract(property),
            IFieldSymbol field => $"field|{NullableIdentity(field.Type)}|{field.DeclaredAccessibility}|{field.IsStatic}|readonly:{field.IsReadOnly}|"
                + $"const:{field.IsConst}|ref:{field.RefKind}|accessSelection:{AccessSelected(field)}",
            _ => "unsupported member kind",
        };
    }

    /// <summary>Explains the pinned producer's namespace-only notification implementation.</summary>
    /// <param name="owner">The original actual owner.</param>
    /// <param name="target">The expected interface identity.</param>
    /// <returns>The missing contract and a supported declaration alternative.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string MissingInterface(INamedTypeSymbol owner, string target) =>
        owner.ContainingType is not null && target == "global::ReactiveUI.IReactiveObject"
            ? "missing interface: ReactiveUI.SourceGenerators 4.2.0 emits [IReactiveObject] implementations at namespace scope; "
                + "use a top-level generated class or explicitly declare the ReactiveObject base/IReactiveObject implementation"
            : "missing interface";

    /// <summary>Checks the exact implemented-interface type identity.</summary>
    /// <param name="owner">The generated owner.</param>
    /// <param name="target">The expected interface identity.</param>
    /// <returns>Whether the interface is actually present.</returns>
    private static bool HasInterface(INamedTypeSymbol owner, string target)
    {
        foreach (var type in owner.AllInterfaces)
        {
            if (ProducerProjection.TypeName(type) == target)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Snapshots the exact property accessor, type and declaring-slot contract.</summary>
    /// <param name="property">The predicted or actual property.</param>
    /// <returns>The deterministic semantic signature.</returns>
    private static string PropertyContract(IPropertySymbol property)
    {
        var index = new List<string>();
        foreach (var parameter in property.Parameters)
        {
            index.Add(NullableIdentity(parameter.Type));
        }

        var implementations = new List<string>();
        foreach (var implementation in property.ExplicitInterfaceImplementations)
        {
            implementations.Add(MemberIdentity(implementation));
        }

        return $"property|{NullableIdentity(property.Type)}|{property.DeclaredAccessibility}|{property.IsStatic}|"
            + $"get:{property.GetMethod?.DeclaredAccessibility}|set:{property.SetMethod?.DeclaredAccessibility}|init:{property.SetMethod?.IsInitOnly}|"
            + $"required:{property.IsRequired}|virtual:{property.IsVirtual}|override:{property.IsOverride}|new:{IsNew(property)}|ref:{property.RefKind}|"
            + $"accessSelection:{AccessSelected(property)}/{AccessSelected(property.GetMethod)}/{AccessSelected(property.SetMethod)}|"
            + $"nullableFlow:{NullableFlow(property)}|index:{string.Join(",", index)}|slot:{MemberIdentity(property.OverriddenProperty)}|"
            + $"explicit:{string.Join(",", implementations)}";
    }

    /// <summary>Preserves forwarded nullable-flow annotations affecting consumer inference.</summary>
    /// <param name="property">The generated property.</param>
    /// <returns>The exact sorted nullable-flow attribute identities.</returns>
    private static string NullableFlow(IPropertySymbol property)
    {
        var names = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var attribute in property.GetAttributes())
        {
            var name = attribute.AttributeClass?.ToDisplayString();
            if (name is "System.Diagnostics.CodeAnalysis.MaybeNullAttribute" or "System.Diagnostics.CodeAnalysis.NotNullAttribute"
                or "System.Diagnostics.CodeAnalysis.AllowNullAttribute" or "System.Diagnostics.CodeAnalysis.DisallowNullAttribute")
            {
                _ = names.Add(name);
            }
        }

        return string.Join(",", names);
    }

    /// <summary>Preserves the producer's explicit hiding declaration contract.</summary>
    /// <param name="property">The declared property.</param>
    /// <returns>Whether its source declaration contains the new modifier.</returns>
    private static bool IsNew(IPropertySymbol property)
    {
        foreach (var reference in property.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is not PropertyDeclarationSyntax declaration)
            {
                continue;
            }

            foreach (var modifier in declaration.Modifiers)
            {
                if (modifier.IsKind(SyntaxKind.NewKeyword))
                {
                    return true;
                }
            }
        }

        return false;
    }

    /// <summary>Identifies the declaring slot, including constructed containing type arguments.</summary>
    /// <param name="member">The overridden or explicitly implemented slot.</param>
    /// <returns>The exact declaring identity, or an empty value.</returns>
    private static string MemberIdentity(ISymbol? member) => member is null ? string.Empty : $"{NullableIdentity(member.ContainingType)}|{member.MetadataName}";

    /// <summary>Records explicit access selection on the actual property or accessor slot.</summary>
    /// <param name="symbol">The selected member or accessor.</param>
    /// <returns>Whether the actual runtime marker is present.</returns>
    private static bool AccessSelected(ISymbol? symbol)
    {
        if (symbol is null)
        {
            return false;
        }

        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass is { } type
                && type.ContainingAssembly.Name is "ReactiveUI.Validation" or "ReactiveUI.Validation.Reactive"
                && type.ToDisplayString() == $"{type.ContainingAssembly.Name}.Capabilities.GeneratedValidationAccessAttribute")
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Distinguishes nullable annotations recursively, including oblivious platform declarations.</summary>
    /// <param name="type">The semantic type.</param>
    /// <returns>The complete nullable identity.</returns>
    private static string NullableIdentity(ITypeSymbol type)
    {
        var arguments = new List<string>();
        if (type is INamedTypeSymbol named)
        {
            foreach (var argument in named.TypeArguments)
            {
                arguments.Add(NullableIdentity(argument));
            }

            if (named.ContainingType is { } containing)
            {
                arguments.Add($"containing={NullableIdentity(containing)}");
            }
        }
        else if (type is IArrayTypeSymbol array)
        {
            arguments.Add(NullableIdentity(array.ElementType));
        }

        return $"{ProducerProjection.TypeName(type)}[{type.NullableAnnotation};{string.Join(",", arguments)}]";
    }

    /// <summary>Escapes an inert compiler contract record.</summary>
    /// <param name="value">The contract value.</param>
    /// <returns>The escaped source literal.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
}
