// <auto-generated/>
#pragma warning disable
namespace ReactiveUI.Binding.Generated.Interceptors.GeneratorInterop.Primitives
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static partial class __ReactiveUIGeneratedBindings
    {
    }
}
