// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Runic.Validation.Verification;

/// <summary>Produces a real peer caller of explicitly registered normal validation APIs.</summary>
[Generator]
public sealed class PeerRegisteredCallerGenerator : IIncrementalGenerator
{
    /// <summary>The original consumer type that opts into this bounded verification producer.</summary>
    private const string ModelMetadataName = "PeerGeneratedCallerModel";

    /// <summary>The selected primitive runtime metadata type.</summary>
    private const string PrimitiveRuntime = "ReactiveUI.Validation.Capabilities.ValidationRuntime";

    /// <summary>The selected System.Reactive runtime metadata type.</summary>
    private const string ReactiveRuntime = "ReactiveUI.Validation.Reactive.Capabilities.ValidationRuntime";

    /// <summary>The generated caller source identity retained by compiler and package gates.</summary>
    private const string HintName = "PeerRegisteredRuleCaller.g.cs";

    /// <summary>The source namespace replacement token.</summary>
    private const string RootToken = "__VALIDATION_ROOT__";

    /// <summary>The actual peer output; registered normal calls deliberately remain unintercepted.</summary>
    private const string CallerSource = """
        // <auto-generated/>
        #nullable enable
        using System;
        using System.Linq.Expressions;
        using __VALIDATION_ROOT__.Capabilities;
        using __VALIDATION_ROOT__.Extensions;
        using __VALIDATION_ROOT__.Helpers;
        using __VALIDATION_ROOT__.States;

        [ValidationRuntimeDispatch]
        internal static class PeerRegisteredRuleCaller
        {
            internal static ValidationHelper Attach(
                PeerGeneratedCallerModel model,
                Expression<Func<PeerGeneratedCallerModel, string?>> expression) =>
                model.ValidationRule(expression, value => value == "peer-ok", "peer-required");

            internal static ValidationHelper AttachTyped(PeerGeneratedCallerModel model) =>
                ValidationRuntime.RegisterRule(model, model.ValidationContext, Selector(),
                    value => value == "peer-ok" ? ValidationState.Valid : new ValidationState(false, "peer-required"));

            internal static ValidationSelector<PeerGeneratedCallerModel, string?> Selector() => new(source =>
                new ValidationAccessPlan<string?>(
                    () => ValidationRead<string?>.Present(source.Text, new[] { ValidationPath.Legacy(nameof(PeerGeneratedCallerModel.Text)) }),
                    new[] { ValidationDependency.PropertyChanged(() => source, nameof(PeerGeneratedCallerModel.Text)) },
                    ValidationObservationOptions<string?>.Default));
        }
        """;

    /// <summary>Registers a finite producer driven by original model and selected runtime symbols.</summary>
    /// <param name="context">The actual compiler's incremental context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var roots = context.CompilationProvider.Select(static (compilation, _) =>
        {
            if (compilation.GetTypeByMetadataName(ModelMetadataName) is null)
            {
                return string.Empty;
            }

            if (compilation.GetTypeByMetadataName(ReactiveRuntime) is not null)
            {
                return "ReactiveUI.Validation.Reactive";
            }

            return compilation.GetTypeByMetadataName(PrimitiveRuntime) is null ? string.Empty : "ReactiveUI.Validation";
        });
        context.RegisterSourceOutput(roots, static (production, root) =>
        {
            if (root.Length != 0)
            {
                production.AddSource(HintName, SourceText.From(CallerSource.Replace(RootToken, root), Encoding.UTF8));
            }
        });
    }
}
