<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>GeneratorInterop.Primitives</AssemblyName><DefineConstants>$(DefineConstants)</DefineConstants></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Runic.ReactiveUI.Validation" Version="$(ValidationVersion)" />
    <PackageReference Include="Runic.DynamicData" Version="10.0.0-runic.5" />
    <PackageReference Include="ReactiveUI" Version="26.0.1" />
    <PackageReference Include="ReactiveUI.Binding" Version="9.1.0" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="4.2.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
