// <auto-generated/>
using ReactiveUI;
using ReactiveUI.Reactive;

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class View
    {
        /// <inheritdoc cref="ViewModel"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::GeneratorInterop.Model? ViewModel
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }

        /// <inheritdoc cref="Message"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string Message
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }

        /// <inheritdoc cref="Status"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::GeneratorInterop.Presentation? Status
        {
            get => field;
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore
