// <auto-generated/>
using ReactiveUI;
using ReactiveUI.Reactive;

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class Model
    {
        /// <inheritdoc cref="Email"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string Email
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }

        /// <inheritdoc cref="Address"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::GeneratorInterop.Address? Address
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }

        /// <inheritdoc cref="Rule"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper? Rule
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }

        /// <inheritdoc cref="SelectedContext"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext? SelectedContext
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore
