// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.Interceptors.GeneratorInterop.Reactive
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(1, "5IrLXIWesnLFvJ+DD2Qn5CUCAABNb2RlbHMuY3M=")]
        internal static global::ReactiveUI.Binding.Reactive.ObservableAsPropertyHelper<bool> __Intercept_ToProperty_00000DBD2773F97A(
            this global::System.IObservable<bool> target,
            global::GeneratorInterop.Model source,
            global::System.Func<global::GeneratorInterop.Model, bool> property,
            bool initialValue,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property")] string propertyExpression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
            => __ToProperty_00000DBD2773F97A(target, source, initialValue, false, null);


        private static global::ReactiveUI.Binding.Reactive.ObservableAsPropertyHelper<bool> __ToProperty_00000DBD2773F97A(
            global::System.IObservable<bool> target,
            global::GeneratorInterop.Model source,
            bool initialValue,
            bool deferSubscription,
            global::System.Reactive.Concurrency.IScheduler? scheduler)
        {
            // ToProperty: global::GeneratorInterop.Model.DerivedValid raised through ReactiveObject
            return global::ReactiveUI.Binding.Reactive.ObservableAsPropertyHelper<bool>.Create(
                target,
                source,
                (__owner, __value) => global::ReactiveUI.Reactive.IReactiveObjectExtensions.RaisePropertyChanged(((global::GeneratorInterop.Model)__owner), "DerivedValid"),
                (__owner, __value) => global::ReactiveUI.Reactive.IReactiveObjectExtensions.RaisePropertyChanging(((global::GeneratorInterop.Model)__owner), "DerivedValid"),
                initialValue,
                deferSubscription,
                scheduler);
        }

    }
}

namespace System.Runtime.CompilerServices
{
    /// <summary>Binds a generated method to the call site it replaces.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="InterceptsLocationAttribute"/> class.</summary>
        /// <param name="version">The encoding of <paramref name="data"/>.</param>
        /// <param name="data">The call site being replaced.</param>
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
