// <auto-generated/>
#nullable enable
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
{
    public InterceptsLocationAttribute(int version, string data) { }
}
}
namespace ReactiveUI.Validation.Generated.Assembly_GeneratorInterop_Reactive
{
    internal static class ValidationInterceptors
    {
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMl0NAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper Intercept0(this global::GeneratorInterop.Model @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.String?>> @viewModelProperty, global::System.Func<global::System.String?, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = ((global::ReactiveUI.Validation.Reactive.Abstractions.IValidatableViewModel)@viewModel).ValidationContext;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.Observe<global::System.String?>(
        () => @viewModel.@Email, new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel, "Email"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.Reactive.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.Reactive.States.ValidationState(false, @message),
        new string[] { "Email" });
}
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMgIOAABQcm9ncmFtLmNz")]
internal static global::System.IDisposable Intercept1(this global::GeneratorInterop.View @view, global::GeneratorInterop.Model? @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.String>> @viewModelProperty, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.View, global::System.String>> @viewProperty)
{
    global::System.ArgumentNullException.ThrowIfNull(@view);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@viewProperty);
    var sources = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.ObserveReference<global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext>(
        () => ((global::ReactiveUI.Validation.Reactive.Abstractions.IValidatableViewModel?)(((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel))?.ValidationContext,
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(@view), "ViewModel"),
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel), "ValidationContext"));
    var resolvedFormatter = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationBindingSupport.ResolveFormatter(null);
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationBindingExtensions.BindObservablePropertyValidationState(sources, static source => source, "Email", states => global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationBindingSupport.FirstNonEmptyMessage(states, resolvedFormatter), value => @view.@Message = value, true);
}

[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMmgOAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.ValidationBindings.Abstractions.IValidationBinding Intercept2(this global::GeneratorInterop.View @view, global::GeneratorInterop.Model? @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper?>> @helperProperty, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.View, global::GeneratorInterop.Presentation?>> @viewProperty, global::System.Func<global::ReactiveUI.Validation.Reactive.States.IValidationState, global::GeneratorInterop.Presentation?> @converter)
{
    global::System.ArgumentNullException.ThrowIfNull(@view);
    global::System.ArgumentNullException.ThrowIfNull(@helperProperty);
    global::System.ArgumentNullException.ThrowIfNull(@viewProperty);
    global::System.ArgumentNullException.ThrowIfNull(@converter);
    var sources = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.ObserveReference<global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper>(
        () => ((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel?.@Rule,
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(@view), "ViewModel"),
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel), "Rule"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationBindingExtensions.BindObservableValidationState(sources, static source => source.ValidationChanged, @converter, value => @view.@Status = value);
}

[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMggRAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper Intercept3(this global::GeneratorInterop.Model @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.String?>> @viewModelProperty, global::System.Func<global::System.String?, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = ((global::ReactiveUI.Validation.Reactive.Abstractions.IValidatableViewModel)@viewModel).ValidationContext;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.Observe<global::System.String?>(
        () => (@viewModel.@Address is null ? default : @viewModel.@Address.@Postcode), new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel, "Address"), new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel.@Address, "Postcode"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.Reactive.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.Reactive.States.ValidationState(false, @message),
        new string[] { "Address.Postcode" });
}
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMk0TAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper Intercept4(this global::GeneratorInterop.Model @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.Boolean>> @viewModelProperty, global::System.Func<global::System.Boolean, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = ((global::ReactiveUI.Validation.Reactive.Abstractions.IValidatableViewModel)@viewModel).ValidationContext;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.Observe<global::System.Boolean>(
        () => @viewModel.@DerivedValid, new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel, "DerivedValid"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.Reactive.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.Reactive.States.ValidationState(false, @message),
        new string[] { "DerivedValid" });
}
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMggVAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper Intercept5(this global::GeneratorInterop.Model @viewModel, global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext @context, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.String?>> @viewModelProperty, global::System.Func<global::System.String?, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = @context;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.Observe<global::System.String?>(
        () => @viewModel.@Email, new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel, "Email"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.Reactive.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.Reactive.States.ValidationState(false, @message),
        new string[] { "Email" });
}
[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMhwWAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.ValidationBindings.Abstractions.IValidationBinding Intercept6(this global::GeneratorInterop.View @view, global::GeneratorInterop.Model? @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext?>> @contextProperty, global::System.Action<global::ReactiveUI.Validation.Reactive.States.IValidationState> @action)
{
    global::System.ArgumentNullException.ThrowIfNull(@view);
    global::System.ArgumentNullException.ThrowIfNull(@contextProperty);
    global::System.ArgumentNullException.ThrowIfNull(@action);
    var sources = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.ObserveReference<global::ReactiveUI.Validation.Reactive.Contexts.IValidationContext>(
        () => ((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel?.@SelectedContext,
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(@view), "ViewModel"),
        new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => (global::System.ComponentModel.INotifyPropertyChanged?)(((global::ReactiveUI.Binding.Reactive.IViewFor<global::GeneratorInterop.Model>)@view).ViewModel), "SelectedContext"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationBindingExtensions.BindObservableValidationState(sources, static source => source.ValidationStatusChange, static state => state, @action);
}

[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "Pijn/wi1E5qPR5EQDL4tMq4aAABQcm9ncmFtLmNz")]
internal static global::ReactiveUI.Validation.Reactive.Helpers.ValidationHelper Intercept7(this global::GeneratorInterop.Model @viewModel, global::System.Linq.Expressions.Expression<global::System.Func<global::GeneratorInterop.Model, global::System.String?>> @viewModelProperty, global::System.Func<global::System.String?, global::System.Boolean> @isPropertyValid, global::System.String @message)
{
    global::System.ArgumentNullException.ThrowIfNull(@viewModel);
    global::System.ArgumentNullException.ThrowIfNull(@viewModelProperty);
    global::System.ArgumentNullException.ThrowIfNull(@isPropertyValid);
    global::System.ArgumentException.ThrowIfNullOrEmpty(@message);
    var capturedContext = ((global::ReactiveUI.Validation.Reactive.Abstractions.IValidatableViewModel)@viewModel).ValidationContext;
    global::System.ArgumentNullException.ThrowIfNull(capturedContext);
    var values = global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationObservation.Observe<global::System.String?>(
        () => @viewModel.@Email, new global::ReactiveUI.Validation.Reactive.Extensions.GeneratedValidationProperty(() => @viewModel, "Email"));
    return global::ReactiveUI.Validation.Reactive.Extensions.ObservableValidationRuleExtensions.AddObservableRule(
        capturedContext, values,
        value => @isPropertyValid(value) ? global::ReactiveUI.Validation.Reactive.States.ValidationState.Valid
            : new global::ReactiveUI.Validation.Reactive.States.ValidationState(false, @message),
        new string[] { "Email" });
}

} }