// <auto-generated/>

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class GeneratedOnlyModel
    {
        private global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid>? _submitCommand;

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveCommandGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.ReactiveCommand<global::ReactiveUI.Primitives.RxVoid, global::ReactiveUI.Primitives.RxVoid> SubmitCommand { get => _submitCommand ??= global::ReactiveUI.ReactiveCommand.Create(Submit); }
    }
}
#nullable restore
#pragma warning restore
