// <auto-generated/>
using ReactiveUI;
using ReactiveUI.Reactive;

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class Address
    {
        /// <inheritdoc cref="Postcode"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial string Postcode
        {
            get => field;
            [global::System.Diagnostics.CodeAnalysis.MemberNotNull("field")]
            set
            {
                this.RaiseAndSetIfChanged(ref field, value);
            }
        }
    }
}
#nullable restore
#pragma warning restore
