// <auto-generated/>
#pragma warning disable
#nullable enable

using System;

namespace ReactiveUI.Binding.Generated.Interceptors.ProjectionConsumer_Reactive_adapter_first
{
    internal static partial class __ReactiveUIGeneratedBindings
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(1, "cCJZ/5ebwPhKtwNn9bMDONgCAABPcmlnaW5hbElucHV0LmNz")]
        internal static global::System.IObservable<string> __Intercept_WhenAnyValue_7FFFEBDF87256747(
            this global::ProjectionInput.Model objectToMonitor,
            global::System.Linq.Expressions.Expression<global::System.Func<global::ProjectionInput.Model, string?>> property1,
            [global::System.Runtime.CompilerServices.CallerArgumentExpression("property1")] string property1Expression = "",
            [global::System.Runtime.CompilerServices.CallerFilePath] string callerFilePath = "",
            [global::System.Runtime.CompilerServices.CallerLineNumber] int callerLineNumber = 0)
            => __WhenAnyValue_7FFFEBDF87256747(objectToMonitor);


        private static global::System.IObservable<string> __WhenAnyValue_7FFFEBDF87256747(global::ProjectionInput.Model obj)
        {
            return (global::ReactiveUI.Binding.Reactive.Fallback.ObservationAffinityChecker.FindHigherAffinityPlugin(obj.GetType(), "Name", 10, false) is global::ReactiveUI.Binding.Reactive.ICreatesObservableForProperty __registration_obj
                ? (global::System.IObservable<string>)new global::ReactiveUI.Binding.Reactive.Observables.PluginPropertyObservable<string>(
                    __registration_obj,
                    obj,
                    ((global::System.Linq.Expressions.Expression<global::System.Func<global::ProjectionInput.Model, string>>)(__e => __e.Name)).Body,
                    "Name",
                    (object __o) => ((global::ProjectionInput.Model)__o).Name,
                    false, false)
                : (global::System.IObservable<string>)
                new global::ReactiveUI.Binding.Reactive.Observables.PropertyObservable<string>(obj, "Name", (global::System.ComponentModel.INotifyPropertyChanged __o) => ((global::ProjectionInput.Model)__o).Name, true));
        }

    }
}

namespace System.Runtime.CompilerServices
{
    /// <summary>Binds a generated method to the call site it replaces.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        /// <summary>Initializes a new instance of the <see cref="InterceptsLocationAttribute"/> class.</summary>
        /// <param name="version">The encoding of <paramref name="data"/>.</param>
        /// <param name="data">The call site being replaced.</param>
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
