<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>ValidationAot.Primitives</AssemblyName></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Runic.ReactiveUI.Validation" Version="8.1.0-runic.0.790.17" />
    <PackageReference Include="ReactiveUI" Version="26.0.1" />
    <PackageReference Include="Runic.DynamicData" Version="10.0.0-runic.5" />
  </ItemGroup>
</Project>
