// <auto-generated/>
#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    partial class Model
    {
        /// <summary>Backs <see cref="DerivedValid"/>; assign it with <c>ToProperty</c>.</summary>
        private global::ReactiveUI.Binding.Reactive.ObservableAsPropertyHelper<bool>? _derivedValidHelper;

        public partial bool DerivedValid => _derivedValidHelper is null ? default! : _derivedValidHelper.Value;
    }
}
