<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'ReactiveUI.Validation' or '$(MSBuildProjectName)' == 'ReactiveUI.Validation.Reactive'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)ReactiveUI.Validation.SourceGenerators/ReactiveUI.Validation.SourceGenerators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" PrivateAssets="all" />
    <None Include="$(MSBuildThisFileDirectory)ReactiveUI.Validation.SourceGenerators/bin/$(Configuration)/netstandard2.0/ReactiveUI.Validation.SourceGenerators.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn5.9/cs" />
    <None Include="$(MSBuildThisFileDirectory)ReactiveUI.Validation.SourceGenerators/buildTransitive/Runic.ReactiveUI.Validation.props" Pack="true" PackagePath="buildTransitive/$(PackageId).props" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsTestProject)' == 'true' and '$(MSBuildProjectName)' != 'ReactiveUI.Validation.SourceGenerators.Tests'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)ReactiveUI.Validation.SourceGenerators/ReactiveUI.Validation.SourceGenerators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" PrivateAssets="all" />
  </ItemGroup>
  <PropertyGroup>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
    <AndroidUseIntermediateDesignerFile>False</AndroidUseIntermediateDesignerFile>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.StartsWith('netstandard'))">
    <DefineConstants>$(DefineConstants);NETSTANDARD</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <DefineConstants>$(DefineConstants);NET_461;XAML</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('uap'))">
    <DefineConstants>$(DefineConstants);NETFX_CORE;XAML;WINDOWS_UWP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('Xamarin.iOS'))">
    <DefineConstants>$(DefineConstants);MONO;UIKIT;COCOA</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('Xamarin.Mac'))">
    <DefineConstants>$(DefineConstants);MONO;COCOA</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('Xamarin.TVOS'))">
    <DefineConstants>$(DefineConstants);MONO;UIKIT;COCOA</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('Xamarin.WatchOS'))">
    <DefineConstants>$(DefineConstants);MONO;UIKIT;COCOA</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('MonoAndroid'))">
    <DefineConstants>$(DefineConstants);MONO;ANDROID</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('tizen'))">
    <DefineConstants>$(DefineConstants);TIZEN</DefineConstants>
  </PropertyGroup>
</Project>
