// <auto-generated/>

#pragma warning disable
#nullable enable

namespace GeneratorInterop
{
    internal partial class GeneratedOnlyModel
    {
        private global::ReactiveUI.Reactive.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit>? _submitCommand;

        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ReactiveCommandGenerator", "4.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::ReactiveUI.Reactive.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> SubmitCommand { get => _submitCommand ??= global::ReactiveUI.Reactive.ReactiveCommand.Create(Submit); }
    }
}
#nullable restore
#pragma warning restore
