<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><DefineConstants>$(DefineConstants);REACTIVE_SHIM</DefineConstants></PropertyGroup>
  <ItemGroup>
    <Compile Include="../Program.cs" Link="Program.cs" />
    <PackageReference Include="Runic.ReactiveUI.Validation.Reactive" />
    <PackageReference Include="Runic.DynamicData.Reactive" />
    <PackageReference Include="ReactiveUI.Reactive" Condition="'$(UseReactiveUIReference)' == 'true'" />
    <PackageReference Include="ReactiveUI.SourceGenerators" PrivateAssets="all" Condition="'$(UseVmGenerator)' == 'true'" />
  </ItemGroup>
</Project>
