//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("GeneratedValidation.LegacyPeer.Primitives")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+7892134cc56e65b58df7e35215ff480175544180")]
[assembly: System.Reflection.AssemblyProductAttribute("GeneratedValidation.LegacyPeer.Primitives")]
[assembly: System.Reflection.AssemblyTitleAttribute("GeneratedValidation.LegacyPeer.Primitives")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

